# Lidando com vetores (lista de números)

Renato Naville Watanabe

Para trabalhar com vetores, vamos utilizar a biblioteca Numpy. Para utilizá-la, devemos importá-ĺa:

In [1]:
import numpy

Como o termo numpy é muito grande, é muito comum usar um *alias* ("apelido") para essa biblioteca. Normalmente o *alias* usado é np.

In [2]:
import numpy as np

Dessa forma, sempre que for utilizar a biblioteca numpy, não é necessário escrever numpy e sim np.

## Vetores

Com a biblioteca Numpy você pode criar vetores. 
Com o comando 'np.array' você cria vetores digitando cada elemento pertencente ao vetor:

In [3]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


Com o comando 'np.arange', você cria vetores especificando os limites e o intervalo entre os elementos. Por exemplo, para criar um vetor que vai de 0 a 12 com intervalo entre os elementos de 0,2, deve-se digitar:

In [4]:
y = np.arange(0, 12, 0.2)
print(y)

[ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.
 11.2 11.4 11.6 11.8]


Com o comando 'np.linspace', você cria vetores especificando os limites e o número de elementos. Por exemplo, para criar um vetor que vai de 0 a 11 com 130 elementos, deve-se digitar:

In [5]:
z = np.linspace(0, 11, 130)
print(z)

[ 0.          0.08527132  0.17054264  0.25581395  0.34108527  0.42635659
  0.51162791  0.59689922  0.68217054  0.76744186  0.85271318  0.9379845
  1.02325581  1.10852713  1.19379845  1.27906977  1.36434109  1.4496124
  1.53488372  1.62015504  1.70542636  1.79069767  1.87596899  1.96124031
  2.04651163  2.13178295  2.21705426  2.30232558  2.3875969   2.47286822
  2.55813953  2.64341085  2.72868217  2.81395349  2.89922481  2.98449612
  3.06976744  3.15503876  3.24031008  3.3255814   3.41085271  3.49612403
  3.58139535  3.66666667  3.75193798  3.8372093   3.92248062  4.00775194
  4.09302326  4.17829457  4.26356589  4.34883721  4.43410853  4.51937984
  4.60465116  4.68992248  4.7751938   4.86046512  4.94573643  5.03100775
  5.11627907  5.20155039  5.28682171  5.37209302  5.45736434  5.54263566
  5.62790698  5.71317829  5.79844961  5.88372093  5.96899225  6.05426357
  6.13953488  6.2248062   6.31007752  6.39534884  6.48062016  6.56589147
  6.65116279  6.73643411  6.82170543  6.90697674  6.9

Para saber qual o tamanho de um vetor, use o comando 'len'.

In [6]:
len(z)

130

## Funções matemáticas

As funções da biblioteca math não se aplicam a vetores. Se você tentar usar a biblioteca math em vetores, aparecerá um erro:


In [8]:
import math
y = math.sin(x)
print(y)

TypeError: only size-1 arrays can be converted to Python scalars

Porém, a biblioteca Numpy contém funções matemáticas também (na verdade a biblioteca Numpy contém muito mais funções do que biblioteca Math). Essas funções se aplicam a vetores. Neste caso, a função é aplicada a cada um dos elementos do vetor e tem como resultado um vetor do mesmo tamanho do vetor original.

**Potência**


In [14]:
print('x=', x)
print('x²=', x**2)

x= [1 2 3 4 5]
x²= [ 1  4  9 16 25]


**Exponencial**: exp($x$)=$e^x$ em que $e=2,7182...$ 

In [19]:
print('x=', x)
print('e^x=',np.exp(x))

x= [1 2 3 4 5]
e^x= [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


**Raiz quadrada**: $\sqrt{x}$

In [20]:
s = np.sqrt(x)
print('x=',x)
print('raiz=',s)

x= [1 2 3 4 5]
raiz= [1.         1.41421356 1.73205081 2.         2.23606798]


**Funções trigonométricas**

Em todas as funções trigonométricas, o ângulo deve estar em radianos. Abaixo seno e cosseno.

In [22]:
d = np.sin(x)
g = np.cos(x)
print('x=', x)
print('sen(x)=', d)
print('cos(x)=', g)

x= [1 2 3 4 5]
sen(x)= [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos(x)= [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


**Valor absoluto**

In [24]:
a = np.abs(d)
print('d=',d)
print('|d|=',a)

d= [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
|d|= [0.84147098 0.90929743 0.14112001 0.7568025  0.95892427]


## Operações entre vetores

As operações aritméticas básicas (+, -, /, $*$, %, $**$ ) também podem ser utilizados entre vetores que tenham o mesmo formato. Neste caso, as operações são realizadas entre os elementos que correspondem à mesma posição nos dois vetores.

In [26]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

z = x + y
print('x=', x)
print('y=', y)
print('x+y=', z)

x= [1 2 3 4 5]
y= [ 6  7  8  9 10]
x+y= [ 7  9 11 13 15]


In [28]:
w = x * y
print('x=', x)
print('y=', y)
print('x*y=', w)

x= [1 2 3 4 5]
y= [ 6  7  8  9 10]
x*y= [ 6 14 24 36 50]


In [30]:
k = x - y
print('x=',x)
print('y=',y)
print('x-y=',k)

x= [1 2 3 4 5]
y= [ 6  7  8  9 10]
x-y= [-5 -5 -5 -5 -5]


In [31]:
m = y/x
print('x=', x)
print('y=', y)
print('y/x=', m)

x= [1 2 3 4 5]
y= [ 6  7  8  9 10]
y/x= [6.         3.5        2.66666667 2.25       2.        ]


In [32]:
r = y%x
print('x=', x)
print('y=', y)
print('resto de y por x=', r)

x= [1 2 3 4 5]
y= [ 6  7  8  9 10]
resto de y por x= [0 1 2 1 0]


In [33]:
p = x**y
print('x=', x)
print('y=', y)
print('x^y', p)

x= [1 2 3 4 5]
y= [ 6  7  8  9 10]
x^y [      1     128    6561  262144 9765625]


##  Operações em vetores

Existem algumas funções da biblioteca Numpy que funcionam apenas em vetores.

**Função máximo e função mínimo**

In [20]:
x = np.array([10,2,32,41,15])

y = np.max(x)
z = np.min(x)
print(x)


print('O máximo de x é', y)
print('O mínimo de x é', z)

[10  2 32 41 15]
O máximo de x é 41
O mínimo de x é 2


**Função soma**

Obtém a somatória de todos os elementos do vetor.

In [21]:
x = np.array([10,2,32,41,15])

y = np.sum(x)
print(x)

print('A somatória dos elementos de x é', y)

[10  2 32 41 15]
A somatória dos elementos de x é 100


### Acessar um elemento de um vetor

Para acessar um elemento específico de um vetor basta digitar o nome do vetor e, entre colchetes, a posição do elemento no vetor. 

In [34]:
x = np.array([4, 7, 21, 87, 2, -10])

print(x)

print(x[3])

[  4   7  21  87   2 -10]
87


O primeiro elemento de um vetor tem a posição 0:

In [35]:
print(x[0])

4


Para acessar o terceiro elemento do vetor (posição 2), basta:

In [23]:
print(x)

print(x[2])

[  4   7  21  87   2 -10]
21


O último elemento de um vetor é acessado usando o índice -1:

In [24]:
print(x)
print(x[-1])

[  4   7  21  87   2 -10]
-10


## Referências

- Chalco, JM, *Slides de Bases Computacionais da Ciência*, (2014)
- Leite, S, *Slides de Bases Computacionais da Ciência*, (2018)
- [Marietto, MGB et al.; **Bases computacionais da Ciência** (2013)](http://prograd.ufabc.edu.br/images/pdf/bases_computacionais_livro.pdf).
- [Duarte, M, *Python para computação científica* (2017)](https://nbviewer.jupyter.org/github/BMClab/bmc/blob/master/notebooks/PT-BR/PythonForScientificComputing_PT-BR.ipynb)
- [Matplotlib Gallery](https://matplotlib.org/stable/gallery/index.html)